# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeFoodUniversity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'DropDown'
  pod 'FirebaseUI'
  # Pods for FreeFoodUniversity

  target 'FreeFoodUniversityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeFoodUniversityUITests' do
    # Pods for testing
  end

end
